### PR TITLE
Accept 1.0.0-rc1 in version parser

### LINKED ISSUE #20: vscode extension can not parse the latest buf binary version
## Reproduce 

* Install the latest buf binary (v1.0.0-rc1)
* Install the buf-vscode extension 
* buf-vscode throws a error: `Failed to get buf version: failed to parse version output: 1.0.0-rc1`

## Possible Fix

Why not use the standard semver regexp rules suggested by [semver](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) ?

Addressed here: https://regex101.com/r/vkijKf/1/

### PR DESCRIPTION
**Pull request by timostamm**
Fixes #20 and adds coverage.

### CODE REVIEW

File: src/version.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import { Error } from "./errors";
 
-const versionRegexp = /^(\d+)\.(\d+).(\d+)(-dev)?$/;
+// regular expression suggested by semver.org
+const versionRegexp = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;
```
Comment (johanbrandhorst) [inline src/version.ts:5]: Can we just use a simple one that will cover what we need? This is completely unreadable by humans 😂. I doubt we need to support the whole sem ver spec.

**Review by johanbrandhorst — APPROVED** [review]
Thanks for this, I'm just wondering if we can simplify the regex a bit

**Review by johanbrandhorst — APPROVED** [review]
LGTM
